const students = [
  {
    id: 1,
    name: "Student 1",
    registrationNumber: "12345",
    className: "Class A",
    profileImg: "url-to-image-1.jpg",
  },
  {
    id: 2,
    name: "Student 2",
    registrationNumber: "54321",
    className: "Class B",
    profileImg: "url-to-image-2.jpg",
  },
  {
    id: 3,
    name: "Student 3",
    registrationNumber: "98765",
    className: "Class C",
    profileImg: "url-to-image-3.jpg",
  },
  {
    id: 4,
    name: "Student 4",
    registrationNumber: "45678",
    className: "Class A",
    profileImg: "url-to-image-4.jpg",
  },
  {
    id: 5,
    name: "Student 5",
    registrationNumber: "98765",
    className: "Class B",
    profileImg: "url-to-image-5.jpg",
  },

  {
    id: 6,
    name: "Student 6",
    registrationNumber: "98766",
    className: "Class C",
    profileImg: "url-to-image-6.jpg",
  },
  {
    id: 7,
    name: "Student 7",
    registrationNumber: "45679",
    className: "Class A",
    profileImg: "url-to-image-7.jpg",
  },
  {
    id: 8,
    name: "Student 8",
    registrationNumber: "98767",
    className: "Class B",
    profileImg: "url-to-image-8.jpg",
  },
  {
    id: 9,
    name: "Student 9",
    registrationNumber: "54326",
    className: "Class C",
    profileImg: "url-to-image-9.jpg",
  },
  {
    id: 10,
    name: "Student 10",
    registrationNumber: "45680",
    className: "Class A",
    profileImg: "url-to-image-10.jpg",
  },
  {
    id: 11,
    name: "Student 11",
    registrationNumber: "98768",
    className: "Class B",
    profileImg: "url-to-image-11.jpg",
  },
  {
    id: 12,
    name: "Student 12",
    registrationNumber: "54327",
    className: "Class C",
    profileImg: "url-to-image-12.jpg",
  },
  {
    id: 13,
    name: "Student 13",
    registrationNumber: "45681",
    className: "Class A",
    profileImg: "url-to-image-13.jpg",
  },
  {
    id: 14,
    name: "Student 14",
    registrationNumber: "98769",
    className: "Class B",
    profileImg: "url-to-image-14.jpg",
  },
  {
    id: 15,
    name: "Student 15",
    registrationNumber: "54328",
    className: "Class C",
    profileImg: "url-to-image-15.jpg",
  },
  {
    id: 16,
    name: "Student 16",
    registrationNumber: "45682",
    className: "Class A",
    profileImg: "url-to-image-16.jpg",
  },
  {
    id: 17,
    name: "Student 17",
    registrationNumber: "98770",
    className: "Class B",
    profileImg: "url-to-image-17.jpg",
  },
  {
    id: 18,
    name: "Student 18",
    registrationNumber: "54329",
    className: "Class C",
    profileImg: "url-to-image-18.jpg",
  },
  {
    id: 19,
    name: "Student 19",
    registrationNumber: "45683",
    className: "Class A",
    profileImg: "url-to-image-19.jpg",
  },
  {
    id: 20,
    name: "Student 20",
    registrationNumber: "98771",
    className: "Class B",
    profileImg: "url-to-image-20.jpg",
  },
  {
    id: 21,
    name: "Student 21",
    registrationNumber: "54330",
    className: "Class C",
    profileImg: "url-to-image-21.jpg",
  },
  {
    id: 22,
    name: "Student 22",
    registrationNumber: "45684",
    className: "Class A",
    profileImg: "url-to-image-22.jpg",
  },
  {
    id: 23,
    name: "Student 23",
    registrationNumber: "98772",
    className: "Class B",
    profileImg: "url-to-image-23.jpg",
  },
  {
    id: 24,
    name: "Student 24",
    registrationNumber: "54331",
    className: "Class C",
    profileImg: "url-to-image-24.jpg",
  },
  {
    id: 25,
    name: "Student 25",
    registrationNumber: "45685",
    className: "Class A",
    profileImg: "url-to-image-25.jpg",
  },
  {
    id: 26,
    name: "Student 26",
    registrationNumber: "98773",
    className: "Class B",
    profileImg: "url-to-image-26.jpg",
  },
  {
    id: 27,
    name: "Student 27",
    registrationNumber: "54332",
    className: "Class C",
    profileImg: "url-to-image-27.jpg",
  },

  {
    id: 28,
    name: "Student 28",
    registrationNumber: "23456",
    className: "Class A",
    profileImg: "url-to-image-28.jpg",
  },
  {
    id: 29,
    name: "Student 29",
    registrationNumber: "87656",
    className: "Class B",
    profileImg: "url-to-image-29.jpg",
  },
  {
    id: 30,
    name: "Student 30",
    registrationNumber: "34567",
    className: "Class C",
    profileImg: "url-to-image-30.jpg",
  },
];

export default students;
